#'''Parameters config.'''#


# --- general --- #

ext: "/home/lam4003/bin/camp_short-read-taxonomy/workflow/ext"
mask: False 
metaphlan: True 
kraken2: True 
# xtree kingdom options: bacterial_archaeal, viral, protozoa_fungi
# Separate options on one line with commas (ex. viral,protozoa_fungi)
xtree: 


# --- metaphlan --- #

metaphlan_database: "/athena/masonlab/scratch/databases/metagenomics/metaphlan_20220926"


# --- kraken2/bracken --- #

kraken_bracken_database: "/athena/masonlab/scratch/databases/metagenomics/Kraken2"
kraken2_executable: "/home/lam4003/bin/kraken2/kraken2"
read_len: 150


# --- xtree --- #

bacterial_archaeal_database: "/athena/masonlab/scratch/users/btt4001/databases/xtree_db/xtree_db_gtdb207_kmer29_comp2_20220722/GTDB207_filt.xtr"
viral_database: "/athena/masonlab/scratch/users/btt4001/databases/xtree_db/xtree_db_genbankviralcomplete_99percclust_k17_comp0_20220726/genbankviralcomplete_99percclust_k17_comp0_20220726.xtr"
protozoa_fungi_database: "/athena/masonlab/scratch/users/btt4001/databases/xtree_db/xtree_db_genbank_fungi_protozoa_complete_20220726/genbank_fungi_protozoa_complete_20220726.xtr"
xtree_executable: "/home/btt4001/UTree/xtree_recompile"
thresh: 0.02
hthresh : 0.05
uthresh : 0.01
